version: "3.9"

services:
  postgres:
    container_name: postgres-db
    image: postgres:15.2-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"

  s3:
    image: quay.io/minio/minio:RELEASE.2023-04-07T05-28-58Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - s3_data:/data

volumes:
  s3_data: