version: "3.9"

services:
  postgres:
    container_name: postgres-db
    image: postgres:15.2-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      retries: 5
      start_period: 5s

  s3:
    image: quay.io/minio/minio:RELEASE.2023-04-07T05-28-58Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - s3_data:/data

  api:
    container_name: jobs-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: gunicorn jobs_api:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080

  migrate:
    container_name: migrate
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    env_file:
      - .env
    command: alembic upgrade head
    depends_on:
      - postgres


volumes:
  s3_data: