"""Add favorite vacancy relation

Revision ID: af8cefece387
Revises: 158ba7f42034
Create Date: 2023-04-23 23:50:15.944877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af8cefece387"
down_revision = "158ba7f42034"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favorite__vacancy",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("vacancy_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["applicants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vacancy_id"],
            ["vacancies.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "vacancy_id"),
    )
    op.create_index(op.f("ix_favorite__vacancy_user_id"), "favorite__vacancy", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_favorite__vacancy_user_id"), table_name="favorite__vacancy")
    op.drop_table("favorite__vacancy")
    # ### end Alembic commands ###
